spring:
  application:
    name: duhacksbackend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaimin12prajapati@gmail.com
    password: xsqcvtvdedsrsjet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8888